#!/usr/bin/env python

import sys
from os import scandir
from optparse import OptionParser
import avro.schema
from avro.io import DatumWriter
from avro.datafile import DataFileWriter


DEFAULT_SCHEMA_FILENAME = 'originalrecord.avsc'


def process_cmdline(argv):
    if argv is None:
        argv = sys.argv[1:]
    usage="usage: %prog [options] <directory> <output avro file>"
    parser = OptionParser(usage=usage)
    parser.add_option('-s', '--schema', dest='schema_fname',
                      metavar='FILE', help='Schema file name',
                      default=DEFAULT_SCHEMA_FILENAME)
    (options, args) = parser.parse_args(argv)
    if len(args) != 2:
        parser.error('Input directory and output Avro file are required')
    return (options, args)

def convert(dirname, avro_fname, schema):
    with open(avro_fname, 'wb') as outfile:
        writer = DataFileWriter(outfile, DatumWriter(), schema)
        for f in scandir(dirname):
            if f.is_file():
                with open(f.path, 'r') as or_file:
                    writer.append({'body': or_file.read()})
        writer.close()
    
def main(argv=None):
    (options, args) = process_cmdline(argv)
    dirname = args[0]
    avro_fname = args[1]
    schema = avro.schema.Parse(open(options.schema_fname, 'r').read())
    convert(dirname, avro_fname, schema)
    return 0

if __name__ == '__main__':
    status = main()
    sys.exit(status)
